// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Z3iUi9kIw-9zNN0bnRIdVw7TPA0YlHU',
    appId: '1:806765547788:web:eb7e8f851ed9baa39db929',
    messagingSenderId: '806765547788',
    projectId: 'night-out-database',
    authDomain: 'night-out-database.firebaseapp.com',
    storageBucket: 'night-out-database.appspot.com',
    measurementId: 'G-W7LR3BQVXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVKdcfXIQh7gEdxHlheTdG1HbqEJuwEyc',
    appId: '1:806765547788:android:9d523a57d8aff1bd9db929',
    messagingSenderId: '806765547788',
    projectId: 'night-out-database',
    storageBucket: 'night-out-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJmhjPEK2wzrIaXML3QCF5nnA48ZmN_4',
    appId: '1:806765547788:ios:4eab6635262c36989db929',
    messagingSenderId: '806765547788',
    projectId: 'night-out-database',
    storageBucket: 'night-out-database.appspot.com',
    iosBundleId: 'com.example.finalUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJmhjPEK2wzrIaXML3QCF5nnA48ZmN_4',
    appId: '1:806765547788:ios:67aa003dbe5ae3989db929',
    messagingSenderId: '806765547788',
    projectId: 'night-out-database',
    storageBucket: 'night-out-database.appspot.com',
    iosBundleId: 'com.example.finalUi.RunnerTests',
  );
}
